name: Kenzik
favicon: null
layout_spectrum: 0.23739
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose:
  - name: shares
    item: null
    url: null
